name: Run Postman Tests

on:
  push:
    branches: [ main ]

jobs:
  postman-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Newman
      run: npm install -g newman

    - name: Run Postman collection
      run: newman run API_Tutorial/fakestoreproject.postman_collection.json -e API_Tutorial/QA.postman_environment.json
